### ISSUE TITLE
About base.p error

### ISSUE THREAD

**Issue by rrkmiao** [CAOR-MINES-ParisTech/3d-icp-cov#2]
I tried to run your code, but found an error as follows:
Traceback (most recent call last):
  File "/home/XXX/PycharmProjects/ICP_cov/venv/main.py", line 49, in <module>
    icp.results(dataset, sequence, scan_ref, scan_in, Param.cov_ut)
  File "/home/XXX/PycharmProjects/ICP_cov/venv/icp.py", line 93, in results
    cov_base += 1/8*dataset.load(f_base)['cov_base']
  File "/home/XXX/PycharmProjects/ICP_cov/venv/dataset.py", line 53, in load
    with open(file_name, "rb") as file_pi:
FileNotFoundError: [Errno 2] No such file or directory: '/home/XXX/PycharmProjects/ICP_cov/venv/results/Mountain/base.p'

I've checked your code, I haven't figured out where the above file (base.p) is generated.

I'm a beginner for python, and I'm studying your work recently.
Looking forward to your reply, thanks a lot!

**Comment by mbrossar** [comment]
The covariance presents in ['cov_base'] represents a static baseline covariance that can be used as a reference for comparison, see [CELLO-3D:  Estimating  the  Covariance  of  ICP  in  the  Real  World](https://arxiv.org/pdf/1810.01470.pdf).

 This variable is not used in our paper, you can simply remove it. For information, to compute it, I first need to compute results with this part of the line commented. Then, I compute again with code un commented such that cov_base represent a mean covariance (the factor 1/8 correspond to the 8 eight datasets).

**Comment by rrkmiao** [comment]
Thanks a lot for your reply!
